### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by MarkDuchaney** [BlueMalgeran/NotABot#1]
C:\Users\David\Desktop\NotABot-master>node index.js
module.js:657
    throw err;
    ^

 in JSON at position 201vid\Desktop\NotABot-master\settings.json: Unexpected token
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:654:27)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\David\Desktop\NotABot-master\index.js:2:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

C:\Users\David\Desktop\NotABot-master>PAUSE
Press any key to continue . . .

Key is correct

**Comment by jewdev** [comment]
It looks like you did not install your modules correctly or you don't have NodeJS installed.

Please install Node.js 6.0.0 or newer.
And if It's still not working.
Run `npm install` in the cmd when it's in the bot's folder and it will install the dependencies at once.

Please try these solutions out and if you still have an error you can contact me here.
Have a great day 👍 

(If you won't reply after 24 hours this conversation will be closed.)

**Comment by MarkDuchaney** [comment]
Still got the same error

**Comment by jewdev** [comment]
Are you sure you installed the dependencies? Do you have a folder named `node_modules`?

Your installed modules will be in `./my-project/node_modules`

Take a look at `npm`'s documentation and there's a video that can help you get started:
* https://docs.npmjs.com/getting-started/installing-npm-packages-locally
* https://docs.npmjs.com/getting-started/using-a-package.json

Without having `node_modules` in your source directory, you will not be able to run scripts that require them.

**Comment by MarkDuchaney** [comment]
Yes I have everything I need to be able to start the bot, do you have Discord? I'd rather talk on there

**Comment by jewdev** [comment]
Feel free to add me. bluelxrd#6194
For now, I'm going to sleep and I'll talk to you after I wake up.
It's now 2AM for me x_x
![image](https://user-images.githubusercontent.com/28711824/46563927-e8f59800-c90c-11e8-8ed6-9152f0459268.png)

**Comment by jewdev** [comment]
Solved issue in Discord.
Closed! 👍
